[rssx]
port="3000"
dev-mode=false

[mysql]
address="mysql.wiloon.com:3306"

[redis]
address="redis.wiloon.com:6379"

[ui]
path="/home/wiloon/projects/rssx/rssx-client/dist/"

[sync]
# minute
duration=60

[news]
expire-time="-720h"
gc-duration="24h"

[log]
level="debug"
path="/data/rssx/logs/"
file-name="rssx.log"
