[rssx]
port="3000"

[mysql]
address="nuc:3306"

[redis]
address="nuc:6379"

[ui]
path="/home/wiloon/projects/rssx/rssx-client/dist/"

[sync]
# minute
duration=60

[news]
expire-time="-720h"
gc-duration="24h"

[log]
level="info"
path="/data/rssx/logs/"
file-name="rssx.log"