---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rssx-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rssx-api
  template:
    metadata:
      labels:
        name: rssx-api
    spec:
      containers:
        - name: rssx-api-container
          image: registry.wiloon.com/rssx-api:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: rssx-api-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 18081
      targetPort: 8080
      nodePort: 31081
  selector:
    name: rssx-api
