version: '3'

tasks:
  run:
    desc: 在本地启动 RSSX API 服务
    cmds:
      - go run rssx-api.go

  test:
    desc: 运行所有测试
    cmds:
      - go test ./...

  deps:
    desc: 下载依赖
    cmds:
      - go mod download
      - go mod tidy

  container:build:
    desc: 编译 Go 二进制文件
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -o rssx-api rssx-api.go

  container:image:
    desc: 编译容器镜像
    deps: [container:build]
    cmds:
      - nerdctl build -f Containerfile -t rssx-api:latest .

  container:run:
    desc: 运行容器 (需要先创建 .env 文件)
    cmds:
      - nerdctl run --rm --env-file .env -p 8080:8080 rssx-api:latest
