version: '3'

tasks:
  default:
    cmds:
      - task --list

  run:
    desc: 在本地启动 RSSX API 服务
    cmds:
      - go run rssx-api.go

  test:
    desc: 运行所有测试
    cmds:
      - go test ./...

  deps:
    desc: 下载依赖
    cmds:
      - go mod download
      - go mod tidy

  reset-password:
    desc: "重置用户密码 (用法: task reset-password USER=用户名 PASSWORD=密码)"
    cmds:
      - go run tools/reset_password.go -user {{.USER}} -password {{.PASSWORD}}
