-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               10.1.29-MariaDB - MariaDB Server
-- Server OS:                    Linux
-- HeidiSQL Version:             9.4.0.5130
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for rssx
DROP DATABASE IF EXISTS `rssx`;
CREATE DATABASE IF NOT EXISTS `rssx` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;
USE `rssx`;

-- Dumping structure for table rssx.feed
DROP TABLE IF EXISTS `feed`;
CREATE TABLE IF NOT EXISTS `feed` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `url` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table rssx.feed: ~2 rows (approximately)
DELETE FROM `feed`;
/*!40000 ALTER TABLE `feed` DISABLE KEYS */;
INSERT INTO `feed` (`id`, `title`, `url`) VALUES
  (0, 'OS China', 'http://www.oschina.net/news/rss'),
  (1, 'InfoQ', 'http://www.infoq.com/cn/feed');
/*!40000 ALTER TABLE `feed` ENABLE KEYS */;

-- Dumping structure for table rssx.news
DROP TABLE IF EXISTS `news`;
CREATE TABLE IF NOT EXISTS `news` (
  `news_id` int(11) NOT NULL AUTO_INCREMENT,
  `feed_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`news_id`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table rssx.news: ~0 rows (approximately)
DELETE FROM `news`;
/*!40000 ALTER TABLE `news` DISABLE KEYS */;
INSERT INTO `news` (`news_id`, `feed_id`, `title`, `url`, `description`, `create_time`) VALUES
  (1, '0', 'uiw 1.3.4 发布，基于 React 的组件库', 'https://www.oschina.net/news/90924/uiw-react-1-3-4', '<p>新版发布， 高品质的UI工具包，React的组件库，<span style="color:#333333;font-family:-apple-system, &quot;font-size:16px;background-color:#FFFFFF;">为打造高品质的React UI工具包的理想而奋斗！！！</span></p><p><img src="https://static.oschina.net/uploads/space/2017/1126/153306_UP3y_811064.png" alt=""/><br/></p><p>更新内容：</p><ul class=" list-paddingleft-2"><li><p><span style="color:#24292E;font-family:-apple-system, system-ui, &quot;font-size:13.3333px;background-color:#FFFFFF;">Message/Modal/Table组件添加测试用例</span> (<a href="https://github.com/uiw-react/uiw/pull/29">#29</a>) :&nbsp;<a href="https://github.com/kooff88">@kooff88</a>&nbsp;<a href="https://github.com/uiw-react/uiw/commit/c59c9d6fe0ff1c36e411f7b7279b7799ce406a35">c59c9d6</a></p></li><li><p>修复<span style="color:#24292E;font-family:-apple-system, system-ui, &quot;font-size:13.3333px;background-color:#FFFFFF;">Paging组件<span style="color:#24292E;font-family:-apple-system, system-ui, &quot;font-size:13.3333px;background-color:#FFFFFF;">activePage属性无法更新。</span></span>&nbsp;<a href="https://githu', '2017-12-06 23:49:11'),
  (2, '0', 'Eclipse 4.7.2 RC3 发布，新增快速修复程序', 'https://www.oschina.net/news/90923/eclipse-4-7-2-r', '<p>Eclipse 4.7.2 RC3 发布了。值得关注的更新内容：</p><ul class=" list-paddingleft-2"><li><p><a href="http://www.eclipse.org/eclipse/news/4.7.2/#JDT">JDT</a></p></li></ul><p>更新介绍：</p><h3>JDT</h3><ul class=" list-paddingleft-2"><li><p>为未解析类型提供快速修复功能</p></li></ul><p>如果在module-info.java文件的provide指令中有服务提供者的未解析类型，则可以使用新的快速修补程序。 如果在当前模块中找不到未解析的类型，可以使用快速解决方案在当前模块中创建新的类或接口。</p><p>QuickFix 适用于&nbsp;Java9 项目，并且项目具有 module-info.java 文件。</p><p>快速修复可以从编辑器中调用：</p><p><img data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1126/110603_ReK2_2903254.png" src="https://static.oschina.net/uploads/space/2017/1126/110603_ReK2_2903254.png" width="1093" height="685"/></p><p><a href="http://www.eclipse.org/eclipse/news/4.7.2/" target="_self">详情点此查看</a>。</p><p>下载地址：</p><ul class=" list-paddingleft-2"><li><p><a href="http://download.eclipse.org/equinox/drops/M-Oxygen.2RC3-201711230800/" _src="http://download.eclipse.org/equinox/drops/M-Oxygen.2RC3-201711230800/">http://download.eclipse.org/equinox/drops/M-Oxygen.2RC3-201711230800/</a>&n', '2017-12-06 23:49:11'),
  (3, '0', '码云推荐 | 面向企业的类 Jira 问题需求跟踪工具', 'https://gitee.com/actionview/av', '<p>ActionView 提供了一个后端基于php laravel-framework、前端基于reactjs＋redux的类Jira的问题需求跟踪工具。前端代码库：actionview-fe。</p>', '2017-12-06 23:49:11'),
  (4, '0', '每日一博 | 从 0 开始搭建自动部署环境', 'https://my.oschina.net/raindroid/blog/1579639', '<p>从Docker改变使用动态库后，DooD不再可行，而Dind依然可行。针对此改变，重新整理并记录自动部署环境配置步骤。此环境是实现微服务自动部署的基础，使用jenkins持续集成工具，并内置了java和maven，并实现了容器内运行Docker命令的功能。</p>', '2017-12-06 23:49:11'),
  (5, '0', 'QIQI-IM —— 基于 netty4 的在线 IM 解决方案', 'https://www.oschina.net/p/qiqi-im', '<p>QIQIIM 提供简单快捷的 IM 方案，快速打造在线 IM 方案，可用于公司内网、外网通讯，客服系统等，实现了 socket, websocket，可用于任何商业、个人作品中，请保留作者信息，如果项目帮到了您请加个星，文档简陋，后续会不断完善。</p>', '2017-12-06 23:49:11'),
  (6, '0', '协作翻译 | Software 2.0 时代，你准备好了吗？', 'https://www.oschina.net/translate/software-2-0', '<p>我有时会看到人们将神经网络称为“机器学习工具箱中的另一个工具”。他们有一些优点和缺点，他们在这里或那里工作，有时你可以用他们赢得 Kaggle 比赛。不幸的是，这种解释完全错过了森林中的树木。神经网络不仅仅是另一个分类器，它代表了我们如何编写软件的根本转变的开始。他们是 Software 2.0 时代。</p>', '2017-12-06 23:49:11'),
  (7, '0', 'OSChina 周日乱弹 ——被吐槽码农怎么办？', 'https://my.oschina.net/xxiaobian/blog/1579878', '<p>我不会一个人去餐厅，去咖啡厅，去看电影，去吃火锅，去ktv，去看海，去游乐园去搬家，是因为我没钱，最后不做手术是因为病不起。我不会一个人去餐厅，去咖啡厅，去看电影，去吃火锅，去ktv，去看海，去游乐园去搬家，是因为我没钱，最后不做手术是因为病不起。</p>', '2017-12-06 23:49:11'),
  (8, '0', '程序员着装退化史：曾经也是体面人', 'https://www.oschina.net/news/90917/programmer-dres', '<blockquote><p>是什么力量，让任何地方的程序员都享有「免于体面的自由」？</p></blockquote><p><em>文｜陶禹廷</em></p><p>在今天的社会里，工程师往往代表着知识水平和社会地位。每当普通人听到这个头衔，总会报之以敬仰的目光：</p><p><img alt="" height="400" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1126/075625_sBkk_2896879.gif" src="https://static.oschina.net/uploads/space/2017/1126/075625_sBkk_2896879.gif" width="600"/></p><p>但有一种工程师，虽然也是如假包换的高级技术人员，却很少能享受到和同类相近的社交待遇：程序员。</p><p><img alt="" height="784" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1126/075643_nyoV_2896879.gif" src="https://static.oschina.net/uploads/space/2017/1126/075643_nyoV_2896879.gif" width="600"/></p><p>和工程师的耀眼形象不同，多数人眼里的程序员更接近于一群情趣干瘪的宅男，而非高智商高收入的精英群体。网络上嘲笑程序员的段子俯拾皆是，简直发展成了一种文化现象：</p><p><img alt="" height="705" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1126/075708_MBCf_2896879.gif" src="https://static.oschina.net/uploads/space/2017/1126/075708_MBCf_2896879.gif" width="450"/></p><p>客观而言，这些评价并不公正。作为高级技术人员，多数北上广的程序员都能做到月入万元以上，毫不逊色于其他工程师或职业。大多数嘲笑程序员的人，实现阶层逆袭的可能性都远', '2017-12-06 23:49:11'),
  (9, '0', 'Android、iOS 之后，第三大移动系统会重新出现么', 'https://www.oschina.net/news/90916/can-fuchsia-be-', '<p>尽管距离我们第一次了解到 Fuchsia 这个操作系统的存在已经过去了一年，但谷歌仍对开发这个操作系统的意图保持沉默。Fuchsia 是谷歌旗下没啥存在感但又有些神秘的一款操作系统，目前处于开放式开发的状态，但官方一直没啥表态，比如它到底是用来干啥的，又或者是用来取代什么的。</p><p>近日有新闻消息显示，谷歌的 GitHub 存储库进行了一项奇怪的更新，该更新显示谷歌公司使用了 Swift 语言，该公司正致力于在自己的 Fuchsia OS 操作系统中为 Swift 这种编程语言提供支持。</p><p>Swift 是一种由苹果公司开发的编程语言，用于构建 iOS、macOS、tvOS 以及 watchOS 应用程序。WWDC 2014，苹果宣布所有的 iOS 设备都将开始使用一个新的编程语言叫做 Swift。Swift 被称作“快速、现代、安全、可交互的”编程语言，这门语言具有更容易学，编程更有成效的特性。</p><p>在 Swift 之前，iOS 程序基本上是用 Objective-C（OC）写的，这门语言（OC）已经使用了超过 20 年，并且也是 Mac 和 iOS 设备最基本的编程语言。大多数人觉得 OC 太难学了，语法看起来也很怪异，以至于这门代码吓跑了不少刚开始学习 iOS 编程的人。</p><p><img alt="" height="354" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1125/201651_2Fir_2896879.jpg" src="https://static.oschina.net/uploads/space/2017/1125/201651_2Fir_2896879.jpg" width="550"/></p><p>相比之下，Swift 是一款易学易用的编程语言，而且它还是第一套具有与脚本语言同样的表现力和趣味性的系统编程语言。Swift 的设计以安全为出发点，语法和标准库也非常简洁，让编程的流程大大缩短、简化，以避免各种常见的编程错误类别。苹果的想法是用 Swift 诱惑更多的 web 开发者来开发移动软件，实际上如你所见，不断增长的开发者大军证明了 Swift 编程语言的成功。2015 年 12 月 4 日，苹果公司宣布 Swift 编程语言开放源代码。</p><p>Sw', '2017-12-06 23:49:11'),
  (10, '0', '微软 Edge 浏览器将出奇招，看片自动不留痕迹', 'https://www.oschina.net/news/90915/edge-automatica', '<p>在访问某些网站时，我们可能会不希望别人知道我们的浏览记录，这也正是“无痕浏览”的由来。</p><p>据&nbsp;<a href="https://www.neowin.net/news/microsoft-patent-could-let-edge-automatically-hide-your-porn-site-history" target="_blank" textvalue="neowin">neowin</a>&nbsp;消息，微软新的专利可能会使其 Edge 浏览器的无痕浏览提升到一个全新的水平，它不再需要你手动去开启功能，而是在你访问某些网站时，自动启动隐私模式，除了不会让网站追踪，也不会在本地留下缓存、历史信息等记录。</p><p><img alt="" height="338" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1125/213741_CGTN_2896879.jpg" src="https://static.oschina.net/uploads/space/2017/1125/213741_CGTN_2896879.jpg" width="600"/></p><p>该专利提供了13种不同的图纸，展示了不同的浏览模式切换的例子，并有流程图详细说明背后的逻辑。</p><p><img alt="" height="738" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1125/214943_bqIf_2896879.jpg" src="https://static.oschina.net/uploads/space/2017/1125/214943_bqIf_2896879.jpg" width="600"/></p><p>当然，这项专利能否最终落实到产品上还有待确认。最终是否能给&nbsp;Edge 浏览器带来全新的体验，也有待时间来检验。</p>', '2017-12-06 23:49:11'),
  (11, '0', 'Imgur 承认 2014 年曾受黑客攻击，170 万账号失窃', 'https://www.oschina.net/news/90914/notice-of-imgur', '<p>全球知名图片分享网站 Imgur&nbsp;前日在其<a data-cke-saved-href="https://blog.imgur.com/2017/11/24/notice-of-data-breach/" href="https://blog.imgur.com/2017/11/24/notice-of-data-breach/" target="_blank">官方博客</a>上承认 2014 年曾受到黑客攻击，包含邮箱地址和密码的 170万用户账户信息被窃取，建议受影响用户账号尽快重新更改密码。</p><p><img height="431" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1125/193407_EtnF_2896879.png" src="https://static.oschina.net/uploads/space/2017/1125/193407_EtnF_2896879.png" width="586"/></p><p>该泄漏事件在过去四年并未引起媒体和用户的注意，直到11月23日一位安全研究人员向 Imgur 发送了一封电子邮件，表示他发现了包含 Imgur 用户信息的数据。Imgur&nbsp;在进行数据确认后，于11月24日清晨正式确认在 2014 年大约有 170 万的 Imgur 用户帐户被入侵。</p><p>Imgur&nbsp;还表示由于网站并不需要用户提交真实姓名、地址或者手机号码，因此被窃取的信息中并不包含私人信息。</p>', '2017-12-06 23:49:11'),
  (12, '0', '专家：自动化正在带走软件开发者最具价值的判断力', 'https://www.oschina.net/news/90913/software-risk-o', '<p>“对于软件开发人员和设计人员来说，有一种潜意识的倾向，就是将任务进行自动化。他们往往会先自动化任何可以自动化的东西，然后把剩下的再交给自己。”</p><p>这是加州大学圣地亚哥分校设计实验室的创始人兼总监唐·诺曼（Don Norman）在“科技管理”杂志上发表的一篇文章。</p><p>“我们开发和设计系统的目的是为了减少人的判断 - 但我们可能会在这个过程中过多的失去人为判断”，诺曼在最新的 YouTube 视频中指出，“我们更希望将技术设计成为一个合作者，而不是替代者”。许多大型企业迫使人们放弃自己的工作流程或工作方式，无论是好还是坏，都迫使他们进入 ERP 系统的模式。随着人工智能，机器学习，机器过程自动化和预先设定的云服务的兴起，这一问题愈加明显。</p><p>诺曼认为，开发人员和设计人员不应该去减少这些人为的判断，反而应该努力扩大它。技术“接管”人们不擅长的任务的部分，但高层次的目标和限制必须由人类而非机器决定。如果人类的判断受到最近的或独特的事件影响太大，系统可以干预并说： “这有一个建议”，或者“你是否考虑过这种可能性呢？” 人类的判断力和决策力是非常强大的，且多数是正确的。</p><p>他建议开发者和设计师努力在机器效率和人类创造力之间取得平衡：</p><blockquote><p>机器能够快速处理信息，可靠地完成所设计的任务，且不会感到厌倦。人们在需要创造力，和对突发情况和整个周围环境的临时反应方面非常擅长。自动化方法应该将二者不同的优势考虑在内，才能构建出更出色的协作系统。</p></blockquote><p><img alt="" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1126/083222_VWCi_2896879.jpg" src="https://static.oschina.net/uploads/space/2017/1126/083222_VWCi_2896879.jpg"/></p><p>编译自：<a data-cke-saved-href="http://www.zdnet.com/article/software-developers-and-designers-risk-over-automating-enterprises/#ftag=RSSbaffb68" href="', '2017-12-06 23:49:11'),
  (13, '0', 'VirtualBox 5.2.2 更新发布，开源虚拟机', 'https://www.oschina.net/news/90912/virtualbox-5-2-', '<p>VirtualBox 5.2.2 更新发布。VirtualBox是甲骨文（Oracle）公司推出的跨平台开源虚拟化软件，支持GNU/Linux，Windows、macOS和Solaris等各种系统。</p><p>主要更新内容如下：</p><ul class=" list-paddingleft-2"><li><p>用户界面：改进屏幕的高分辨率</p></li><li><p>用户界面：增加了复制光学和软盘映像的功能</p></li><li><p>用户界面：改进虚拟媒体管理器</p></li><li><p>音频：增加了更多的HDA支持(e.g. Haiku)</p></li><li><p>VMM: fixed emulation so that Plan 9 guests can start once more (5.1.0 regression)</p></li><li><p>Storage: fixed regression breaking iSCSI (bug <a class="new ticket" href="https://www.virtualbox.org/ticket/17196" title="defect: iSCSI does not work (new)">#17196</a>)</p></li><li><p>Serial: fixed hanging I/O when using named pipes on Windows (5.2.0 regression; bug <a class="closed ticket" href="https://www.virtualbox.org/ticket/17227" title="defect: Kernel debug problem via pipe to com port =&gt; fixed in SVN/next maintenance (closed: fixed)">#17227</a>)</p></li><li><p>Serial: fixed broken communication with certain devices on Linux hosts</p></li><li><p>USB/OHCI: improved behavior so that the controller state after a V', '2017-12-06 23:49:11'),
  (14, '0', 'Cinnamon 3.6.6 发布，Linux 桌面交互环境', 'https://www.oschina.net/news/90911/cinnamon-3-6-6', '<p>Cinnamon 3.6.6 已发布，Cinnamon 由 Clement Lefebvre，Linux Mint 创始的一个桌面交互环境。基于传统 Linux 桌面布局，采用现代技术构建，并引入创新功能。</p><p>更新内容：</p><ul class=" list-paddingleft-2"><li><p>Sound settings: Assign the selected device to the profile selector.</p></li></ul><p>更多可查阅<a data-cke-saved-href="https://github.com/linuxmint/Cinnamon/blob/master/debian/changelog" href="https://github.com/linuxmint/Cinnamon/blob/master/debian/changelog" target="_blank">更新日志</a></p><p>下载地址：</p><ul class=" list-paddingleft-2"><li><p><a href="https://github.com/linuxmint/Cinnamon/archive/3.6.6.zip" rel="nofollow"><strong>Source code</strong> (zip)</a></p></li><li><p><a href="https://github.com/linuxmint/Cinnamon/archive/3.6.6.tar.gz" rel="nofollow"><strong>Source code</strong> (tar.gz)</a></p></li></ul>', '2017-12-06 23:49:11'),
  (15, '0', 'Enlightenment 0.22.1 发布，自由桌面环境', 'https://www.oschina.net/news/90910/enlightenment-0', '<p>Enlightenment 0.22.1 发布了。主要更新内容如下：</p><p>&nbsp;Carsten Haitzler (4):</p><ul class=" list-paddingleft-2"><li><p>e sys - frix warning for less noise</p></li><li><p>hits: silence warnings about possible null string for strcmp</p></li><li><p>fix mouse hangs after unblank</p></li><li><p>music-control - install properly with meson build with icon</p></li></ul><p>Marcel Hollerbach (2):</p><ul class=" list-paddingleft-2"><li><p>meson: make those scripts executable</p></li><li><p>meson: this version is enough for the things we use in the moment</p></li></ul><p>Massimo Maiurana (1):</p><ul class=" list-paddingleft-2"><li><p>Adding danish strings to desktop files&nbsp;</p></li></ul><p>完整更新内容<a href="https://www.enlightenment.org/news/e0.22.1_release" target="_self">点此</a>查看。</p><p>下载地址：</p><ul class=" list-paddingleft-2"><li><p><a href="https://www.enlightenment.org/download" _src="https://www.enlightenment.org/download">https://www.enlightenment.org/download</a>&nbsp;</p></li></ul><p>Enlightenment 是窗口管理器，Enlightenme', '2017-12-06 23:49:11'),
  (16, '0', 'Snapcraft 2.35 发布，Linux 软件包管理工具', 'https://www.oschina.net/news/90909/snapcraft-2-35-', '<p>Snapcraft 2.35 发布了。该版本包含一些来自核心团队之外的社区贡献。</p><p><strong>主要更新内容包括容器，以及新增命令行，如：</strong></p><ul class=" list-paddingleft-2"><li><p>new command: pack</p></li><li><p>new command: refresh</p></li><li><p>new command: edit-collaborators</p></li></ul><p>还在&nbsp;solus 上新增了对运行snapcraft捕捉的初始支持。<span id="result_box" class="">Snapcraft 目前只在 Ubuntu 16.04 上运行良好，工作人员正在努力增加对其他版本和 Linux 发行版的支持。更多更新内容请查看<a href="https://github.com/snapcore/snapcraft/releases" target="_self">发布主页</a>。</span></p><p><span class="">下载地址：</span></p><p><span class=""></span></p><ul class="release-downloads list-paddingleft-2"><li><p><a href="https://github.com/snapcore/snapcraft/archive/2.35.zip" rel="nofollow">Source code&nbsp;(zip)</a></p></li><li><p><a href="https://github.com/snapcore/snapcraft/archive/2.35.zip" rel="nofollow"></a></p><p><a href="https://github.com/snapcore/snapcraft/archive/2.35.tar.gz" rel="nofollow">Source code&nbsp;(tar.gz)</a></p></li></ul><p>我们知道在现在的Ubuntu桌面中，我们几乎都使用的是debian包． 有的Linux系统上是使用rpm包．在Snappy Ubuntu上，我们使用的包叫做sna', '2017-12-06 23:49:11'),
  (17, '0', 'ReactOS 0.4.7 发布，类 XP 的操作系统', 'https://www.oschina.net/news/90908/reactos-0-4-7', '<p>ReactOS 0.4.7 发布了。ReactOS 是免费的和开源的操作系统，它基于 Windows NT 架构中反映出来的最佳设计理念。ReactOS 完全从零开始编写，它并非基于 Linux 的系统，并且与 UNIX 架构没有共同之处。</p><p>主要更新内容：</p><ul class=" list-paddingleft-2"><li><p>[CORE-4107] - Firefox 3.X/4.X don&#39;t register as default web browsers</p></li><li><p>[CORE-4361] - Total Commander 7.04a &quot;explorer is not responding&quot; error during installation</p></li><li><p>[CORE-4975] - Opera: in v9.64 Speed Dial doesn&#39;t work correctly</p></li><li><p>[CORE-6993] - Flat Assembler (fasm) IDE visual glitch</p></li><li><p>[CORE-7454] - shell32: When the Properties Window of a drive is opened, the contextual menu of other Drives doesn&#39;t appear</p></li><li><p>[CORE-7542] - Shell Executions do not work properly when paths include spaces</p></li><li><p>[CORE-7630] - Opening Networking tab of Windows Task Manager causes ROS to BSOD</p></li></ul><p>更多内容请查看 <a href="https://reactos.org/wiki/ChangeLog-0.4.7" target="_self">ChangeLog</a> 或 <a href="https://reactos.org/wiki/Tests_for_0.4.7" target="_self">W', '2017-12-06 23:49:11'),
  (18, '0', 'NAS4Free 11.1.0.3.4952 发布，​开源网络存储系统', 'https://www.oschina.net/news/90907/nas4free-11-1-0', '<p>NAS4Free 11.1.0.3.4952 发布了。NAS4Free 是一个嵌入开源存储系统的分发版系统，支持跨 Windows、Mac 和类 Unix 系统的分享。包含 ZFS, Software RAID (0,1,5), 磁盘加密, S.M.A.R.T / email 报告等功能。支持协议：CIFS (samba), FTP, NFS, TFTP, AFP, RSYNC, Unison, iSCSI, UPnP, Bittorent (initiator and target) ，这些都可以通过其提供的 Web 界面进行配置。</p><p>主要更新内容：</p><p>BUILD 11.1.0.4.4952&nbsp;</p><p>===================&nbsp;</p><p>Changes:</p><p>&nbsp;- Upgrade to FreeBSD 11.1-RELEASE-P4.&nbsp;</p><p>- Update translations.\n- Some webgui code improvements.&nbsp;</p><p>- Add option to make USB devices available in virtualbox-ose.&nbsp;</p><p>- Add swap mode option for zroot.&nbsp;</p><p>- Add CPU microcode update feature option.&nbsp;</p><p>- Add ability to define access methods for unknown USB mass storage devices.&nbsp;</p><p>- Add syslog.conf webgui pages.&nbsp;</p><p>- Upgrade lcdproc to 0.5.9.&nbsp;</p><p>- Upgrade proftpd to 1.3.6.&nbsp;</p><p>- Upgrade sudo to 1.8.21p2.&nbsp;</p><p>- Upgrade rrdtool to 1.7.0.</p><p><a href="https://sourceforge.net/projects/nas4free/files/NAS4Free', '2017-12-06 23:49:11'),
  (19, '0', 'Kubernetes 1.7.11 和 1.7.12-beta.0，容器集群管理系统', 'https://www.oschina.net/news/90906/kubernetes-1-7-', '<p>Kubernetes 1.7.11 和 1.7.12-beta.0 发布。</p><p>自 1.7.10 以来的主要更新内容如下：</p><ul class=" list-paddingleft-2"><li><p>Bugfix: master startup script on GCP no longer fails randomly due to concurrent iptables invocations. (<a href="https://github.com/kubernetes/kubernetes/pull/55945">#55945</a>, <a href="https://github.com/x13n">@x13n</a>)</p></li><li><p>Fix bug in mounting volumes with GlusterFS plugin (<a href="https://github.com/kubernetes/kubernetes/pull/53292">#53292</a>, <a href="https://github.com/humblec">@humblec</a>)</p></li><li><p>Add /bin/tee symlink to bazel build for busybox, so that CI builds have /bin/tee (<a href="https://github.com/kubernetes/kubernetes/pull/55417">#55417</a>, <a href="https://github.com/justinsb">@justinsb</a>)</p></li><li><p>Reduce log noise produced by prometheus-to-sd, by bumping it to version 0.2.2. (<a href="https://github.com/kubernetes/kubernetes/pull/54635">#54635</a>, <a href="https://github.com/loburm">@loburm</a>)</p></li><li><p>Fix session affinity issue with external lo', '2017-12-06 23:49:11'),
  (20, '0', 'Sequelize 4.22.16 和 4.23.0 发布，Node.js 的 ORM', 'https://www.oschina.net/news/90905/sequelize-4-22-', '<p>Sequelize 4.22.16 和 4.23.0 已发布，Sequelize.js 提供对&nbsp;<a data-cke-saved-href="http://www.oschina.net/p/mysql" href="http://www.oschina.net/p/mysql" target="_blank">MySQL</a>，<a data-cke-saved-href="http://www.oschina.net/p/mariadb" href="http://www.oschina.net/p/mariadb" target="_blank">MariaDB</a>，<a data-cke-saved-href="http://www.oschina.net/p/sqlite" href="http://www.oschina.net/p/sqlite" target="_blank">SQLite</a>&nbsp;和&nbsp;<a data-cke-saved-href="http://www.oschina.net/p/postgresql" href="http://www.oschina.net/p/postgresql" target="_blank">PostgreSQL</a>&nbsp;数据库的简单访问，通过映射数据库条目到对象，或者对象到数据库条目。简而言之，就是 ORM（Object-Relational-Mapper）。Sequelize.js 完全是使用 JavaScript 编写，适用于 Node.js 的环境。</p><p>版本更新内容请关注<a href="https://github.com/sequelize/sequelize/compare/v4.22.16...v4.23.0" target="_self">更新记录</a>。<br/></p><p>下载地址：</p><p>4.22.16</p><ul class=" list-paddingleft-2"><li><p><a href="https://github.com/sequelize/sequelize/archive/v4.22.16.zip" rel="nofollow"><strong>Source code</strong> (zip)</a></p></li><li><', '2017-12-06 23:49:11'),
  (21, '0', 'smart-socket v1.2.0 正式发布，超强性能 AIO 框架', 'https://www.oschina.net/news/90904/smart-socket-1-', '<p>smart-socket V1.2.0,可能还是最轻量级的Java AIO 框架吧。本次更新如下：</p><ol class=" list-paddingleft-2"><li><p>新增编解码辅助工具：DelimiterFrameDecoder、FixedLengthFrameDecoder、StreamFrameDecoder</p></li><li><p>读写异步回调实现类分离，代码逻辑更清晰</p></li><li><p>新增状态机类型：SESSION_CLOSING,SESSION_CLOSED；服务状态精细化监控</p></li><li><p>优化关闭通信服务的处理逻辑</p></li></ol><p><strong>Maven</strong>:</p><pre class="brush:xml; toolbar: true; auto-links: false;">&lt;dependency&gt;\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;groupId&gt;org.smartboot.socket&lt;/groupId&gt;\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;artifactId&gt;aio-core&lt;/artifactId&gt;\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;1.2.0&lt;/version&gt;\n&lt;/dependency&gt;</pre><p><strong><br/></strong></p><p><strong>性能测试报告：</strong></p><p><img src="https://static.oschina.net/uploads/space/2017/1126/002607_3Hb8_2385344.png" alt=""/></p><p>即每分钟传输10G流量的数据，处理3亿+的消息量，平均500W/s（性能测试因服务配置不同会存在差异）。</p><p>文档地址：<a href="http://smartsocket.mydoc.io/" target="_blank">http://smartsocket.mydoc.io/</a>&nbsp;（感谢码云提供那么好的工具）</p><p>源码分支：<a href="https://gitee.com/', '2017-12-06 23:49:11'),
  (22, '0', 'tio-httpserver 0.0.4 发布，用 t-io 实现的高性能 http 服务器', 'https://www.oschina.net/news/90903/tio-httpserver-', '<h4><strong>本次修改点：</strong></h4><ol class=" list-paddingleft-2"><li><p>增加org.tio.http.common.HttpResponse.getContentType()</p></li><li><p>gzip放到DefaultHttpRequestHandler中最后才处理&nbsp;</p></li><li><p>删除HttpResponse.setBodyAndGzip&nbsp;</p></li><li><p>FreemarkerConfig增加后缀判断&nbsp;</p></li><li><p>http头的最大长度改为2048</p></li><li><p>增加对freemarker的支持，主要是用于tio-webpack</p></li><li><p>http增加context和suffix，这样方便nginx做代理</p></li></ol><p>t-io官网就是运行在这个服务器下的：<a data-cke-saved-href="http://www.t-io.org/#/case" href="http://www.t-io.org/#/case" target="_blank">http://www.t-io.org/#/case</a></p><h4><strong>POM坐标</strong><br/></h4><pre>&lt;dependency&gt;\n	&lt;groupId&gt;org.t-io&lt;/groupId&gt;\n	&lt;artifactId&gt;tio-http-server&lt;/artifactId&gt;\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;0.0.4-tio-http&lt;/version&gt;\n&lt;/dependency&gt;</pre>', '2017-12-06 23:49:11'),
  (23, '0', 'Kreogist Mu 1.0.0 Beta 5 发布，跨平台音乐中心', 'https://www.oschina.net/news/90902/kreogist-mu-1-0', '<p>经过了几个月的等待，这一个版本终于发布出来了。此版本添加了若干可调整的选项以及修正了多个问题，具体的更新内容如下：<br/><br/>1、支持保存关闭时的播放状态；<br/>2、支持修改全局字体；<br/>3、支持更改后端缓存长度；<br/>4、支持搜索延迟；<br/>5、支持选择输出设备；<br/>6、支持变更增大/减小音量按钮的调整等级；<br/>7、支持普通模式下不自动播放下一首歌曲；<br/>8、MPV后端现可应用选项中的更改；<br/>9、支持Windows与Mac OS X下的全局快捷键；<br/>10、支持Windows最小化到托盘；<br/>11、改进低性能CPU下退出时仍然播放的问题；<br/>12、修正FFMpeg分析器有可能删除正确信息的问题；<br/>13、修正切换音乐标签过快导致UI显示错误的问题；<br/>14、修正在线歌词获取排序算法错误的问题；<br/>15、修正歌词对话框缩放错误的问题；<br/>16、修正主窗口最小化时恢复窗口大小错误的问题；<br/>17、修正网易云歌词后端导致的队列阻塞问题。<br/><br/>本次发布的二进制版本平台包括 Windows、Mac OS X 以及 Ubuntu Linux 16.04 LTS ，PPA现已同步更新。官网的下载页面中上现已提供Linux下的编译教程以及Ubuntu、Linux Mint的PPA地址。<br/><br/>下载地址：<a data-cke-saved-href="http://kreogist.github.io/Mu/cn/downloads.html" href="http://kreogist.github.io/Mu/cn/downloads.html" target="_blank">http://kreogist.github.io/Mu/cn/downloads.html</a><br/><br/>源代码地址：<br/><a data-cke-saved-href="http://gitee.com/Miyanaga/Mu" href="http://gitee.com/Miyanaga/Mu" target="_blank">http://gitee.com/Miyanaga/Mu</a>&nbsp;（Git@OSC）<br/><a data-cke-saved-href="https://gi', '2017-12-06 23:49:12'),
  (24, '0', 'Wit 2.4.0-beta 发布，Java 模板引擎', 'https://www.oschina.net/news/90901/febit-wit-2-4-0', '<p>\n	Febit Wit 是一个&nbsp;Java&nbsp;平台下的模板引擎，语法类似&nbsp;JavaScript，支持自定义函数，全局变量，Lambda&nbsp;表达式，核心模块轻巧，无第三方依赖，采用BSD开源协议。<br/> </p><pre class="brush:xml; toolbar: true; auto-links: false;">&lt;dependency&gt;\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;groupId&gt;org.febit.wit&lt;/groupId&gt;\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;artifactId&gt;wit-core&lt;/artifactId&gt;\n&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;2.4.0-beta&lt;/version&gt;\n&lt;/dependency&gt;</pre><p>2.4.0-beta 更新内容如下:</p><ul class=" list-paddingleft-2"><li><p>\n		修复: 调整整数的解析, 声明时(直接量)如果溢出会抛出异常 , 例如: var int = 10000000000; // &gt; Integer.MAX_VALUE 溢出, 解析时抛出异常	</p></li><li><p>\n		修复: 动态函数调用现在也可以用于声明常量了: const string = obj.~toString(); // 注意: obj 也必须可以常量化的<br/></p></li><li><p>\n		新增: 新增 EnginePlugin 接口, 并提供了 spi 实现, 默认关闭, 可以通过设置 spiPluginCollector.enable=true 来开启<br/></p></li><li><p>\n		新增: List 添加 length 属性, 统一和数组的行为, `list.length` `list.size` `array.size` 等都是可以的<br/></p></li><li><p>\n		新增: Template 添加丢弃输出的 merge(..)/debug(..) 方法<br/></p></li><li><p>\n		变更: 类 KeyValues 更名为 Vars, Key', '2017-12-06 23:49:12'),
  (25, '0', '码云推荐 | 基于 netty4 的极简易上手网络框架 UJCat', 'https://gitee.com/Foldcc/UJCat', '<p>自己的项目需要网络通讯，但不会socket 怎么办？没问题，除了设置ip和端口外，该框架在使用的时候几乎不用去管网络层，这款框架的目的在于让使用者尽量写自己的业务逻辑，而网络层就算完全不会也没有任何问题。适用于socket通讯初学者或者需要socket通讯的小项目。</p>', '2017-12-06 23:49:12'),
  (26, '0', '每日一博 | 用 Python 实现一个大数据搜索引擎', 'https://my.oschina.net/taogang/blog/1579204', '<p>搜索是大数据领域里常见的需求。Splunk和ELK分别是该领域在非开源和开源领域里的领导者。本文利用很少的Python代码实现了一个基本的数据搜索功能，试图让大家理解大数据搜索的基本原理。</p>', '2017-12-06 23:49:12'),
  (27, '0', 'SQL Operations Studio ——微软跨平台数据管理工具', 'https://www.oschina.net/p/sqlopsstudio', '<p>SQL Operations Studio 是微软开源的一个数据管理工具，支持在 Windows, macOS 和 Linux 上与 SQL Server, Azure SQL DB 和 SQL DW 配合使用。</p>', '2017-12-06 23:49:12'),
  (28, '0', '协作翻译 | 编码过程中需尽量避免的 7 条捷径', 'https://www.oschina.net/translate/7-coding-shortcu', '<p>国外分析网站最近编译并分析了一些最广泛使用的软件度量标准，作为报告的一部分，他们还询问了用户采取了什么捷径，以及哪些是后悔采用的。来看看你中枪了没。</p>', '2017-12-06 23:49:12'),
  (29, '0', 'OSChina 周六乱弹 ——孙悟空脱发是什么体验', 'https://my.oschina.net/xxiaobian/blog/1579638', '<p>在家无聊，想去看个电影，到电影院买票，一张45，给了售票员一张一百，她居然找我10块。我手里拿着钱，和售票员对视5秒钟。。。她用非常惊讶的表情问我：你一个人看电影？？</p>', '2017-12-06 23:49:12'),
  (30, '0', 'Linus Torvalds 就指责他人白痴的过激言论道歉', 'https://www.oschina.net/news/90895/linus-torvalds-', '<p>Linus Torvalds 前些日子在其邮件列表上直接抨击了一些安全开发人员，并称“ <a data-cke-saved-href="http://lkml.iu.edu/hypermail/linux/kernel/1711.2/01701.html" href="http://lkml.iu.edu/hypermail/linux/kernel/1711.2/01701.html" target="_blank">Those security people are f*cking morons</a> ”，其愤怒主要是针对 Google Pixel 安全团队的开发者&nbsp;Kees Cook 。</p><p>事情起源于在关于 Linux Kernel 4.15 的功能讨论上，Kees Cook&nbsp;<a data-cke-saved-href="http://lkml.iu.edu/hypermail/linux/kernel/1711.2/01325.html" href="http://lkml.iu.edu/hypermail/linux/kernel/1711.2/01325.html" target="_blank">递交了</a>加固 usercopy 的 pull request，并敦促 Torvalds 尽快合并。Torvalds 则认为，此类的加固他通常会在最后才会考虑，因为加固触及到了核心东西，他需要时间去检查，而且他不相信安全开发者会做理智的事情，最初的 usercopy 加固就导致了很多问题。</p><p>Linus Torvalds&nbsp;还明确表示不会在 4.15 中合并 usercopy 加固，他不想看到另一个加固导致的混乱。在邮件列表上的后续讨论中，Torvalds 称这些安全人员的许多行为是不可接受的，安全问题主要是 bug，加固项目应该将精力集中在调试上，这帮白痴“先杀再问问题”的做法是错误的。</p><p><img height="698" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1124/175650_RTQt_2896879.png" src="https://static.oschina.net/uploads/space/2017/1124/17565', '2017-12-06 23:49:12'),
  (31, '0', '砸 4 亿上 Win10 ，慕尼黑正式叫停 Linux 开源计划', 'https://www.oschina.net/news/90894/windows-10-swit', '<p>据<a data-cke-saved-href="https://www.techrepublic.com/article/windows-10-switchover-will-cost-linux-champion-munich-50m/" href="https://www.techrepublic.com/article/windows-10-switchover-will-cost-linux-champion-munich-50m/" target="_blank">外媒报道</a>，曾经被视为开源先驱的德国慕尼黑市，在尝试了15年的 Linux 和开源软件后，最终还是撑不下去了，正式决定重返&nbsp;Windows。</p><p>议会已经以50：25投票通过，将拿出 8900 万欧元翻修 IT 基础设施。其中，4930万欧元（约合3.86亿）用于将市政公共电脑全部切换到 Windows 10 操作系统，还有 3970 万欧元用于 IT 经费配套其它 IT 类工作。部署工作预计将于2020年完成。</p><p>市议会称，相比使用基于 Linux 的系统，切换到 Windows 将能让源兼容应用和硬件驱动变得更容易，也能节省必须并存 Windows 和 Linux 的费用。</p><p><img alt="" height="399" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1125/074717_ZleS_2896879.jpg" src="https://static.oschina.net/uploads/space/2017/1125/074717_ZleS_2896879.jpg" width="600"/></p>', '2017-12-06 23:49:12'),
  (32, '0', '滴滴开源基于 Vue.js 的移动端组件库 cube-ui', 'https://www.oschina.net/news/90893/didi-opensource', '<p>继 6 月份开源 <a data-cke-saved-href="https://www.oschina.net/news/86317/didi-opensource-virtualapk" href="https://www.oschina.net/news/86317/didi-opensource-virtualapk" target="_blank">Android 端插件化框架 VirtualAPK</a>&nbsp;后，滴滴近日又开源了第二个项目 —— 基于 Vue.js 实现的移动端组件库 cube-ui 。&nbsp;</p><p><img height="200" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1124/153200_JaDr_2896879.png" src="https://static.oschina.net/uploads/space/2017/1124/153200_JaDr_2896879.png" width="600" border="0" hspace="0" vspace="0" title="" style="width: 600px; height: 200px;"/></p><p>cube-ui 由滴滴内部组件库精炼而生，旨在让移动端开发更容易，让开发人员更专注于业务逻辑的开发，提升研发效率。具备以下特性：</p><ul class=" list-paddingleft-2"><li><p><strong>质量可靠</strong></p><p>由滴滴内部组件库精简提炼而来，经历了业务一年多的考验，并且每个组件都有充分单元测试，为后续集成提供保障。</p></li><li><p><strong>体验极致</strong></p><p>以迅速响应、动画流畅、接近原生为目标，在交互体验方面追求极致。</p></li><li><p><strong>标准规范</strong></p><p>遵循统一的设计交互标准，高度还原设计效果；接口标准化，统一规范使用方式，开发更加简单高效。</p></li><li><p><strong>扩展性强</strong></p><p>支持按需引入和<a data-cke-saved-href="https://didi.github.io/c', '2017-12-06 23:49:12'),
  (33, '0', '美团点评开源 MySQL 极速闪回工具 MyFlash', 'https://www.oschina.net/news/90892/meituandianping', '<p>MyFlash 是由美团点评公司技术工程部开发维护且内部使用的一个回滚 DML 操作的工具，旨在方便且高效地进行数据恢复，已于近日宣布开源。该工具通过解析 v4 版本的 binlog ，完成回滚操作。相对已有的回滚工具，其增加了更多的过滤选项，让回滚更加容易。</p><p>开发团队也在其<a data-cke-saved-href="https://tech.meituan.com/MySQL_flashback%E4%BB%8E%E5%8E%9F%E7%90%86%E5%88%B0%E5%AE%9E%E6%88%98.html" href="https://tech.meituan.com/MySQL_flashback%E4%BB%8E%E5%8E%9F%E7%90%86%E5%88%B0%E5%AE%9E%E6%88%98.html" target="_blank">博客</a>上将&nbsp;MyFlash 与市面上现有的闪回工具进行了对比。目前市面上已有的恢复工具，从实现角度把可划分成如下几类。</p><p>① mysqlbinlog 工具配合 sed、awk 。该方式先将 binlog 解析成类 SQL 的文本，然后使用 sed、awk 把类 SQL 文本转换成真正的 SQL 。</p><ul class=" list-paddingleft-2"><li><p>优点：当 SQL 中字段类型比较简单时，可以快速生成需要的 SQL ，且编程门槛也比较低。</p></li><li><p>缺点：当 SQL 中字段类型比较复杂时，尤其是字段中的文本包含 HTML 代码，用 awk、sed 等工具时，就需要考虑极其复杂的转义等情况，出错概率很大。</p></li></ul><p>② 给数据库源码打 patch 。该方式扩展了 mysqlbinlog 的功能，增加 Flashback 选项。</p><ul class=" list-paddingleft-2"><li><p>优点：复用了 MySQL Server 层中 binlog 解析等代码，一旦稳定之后，无须关心复杂的字段类型，且效率较高。</p></li><li><p>缺点：在修改前，需要对 MySQL 的复制代码结构和细节需要较深的了解。版本比较敏感，在 MySQL 5.6 上做的 patch ，基本不能用于 MySQL 5.7 的回滚操作。升级困', '2017-12-06 23:49:12'),
  (34, '0', '特斯拉 Elon Musk ：确保 AI 不做乱的机率不足 10%', 'https://www.oschina.net/news/90891/the-architect-o', '<p>据<a data-cke-saved-href="http://www.rollingstone.com/culture/features/elon-musk-inventors-plans-for-outer-space-cars-finding-love-w511747" href="http://www.rollingstone.com/culture/features/elon-musk-inventors-plans-for-outer-space-cars-finding-love-w511747" target="_blank">外媒</a>报道，特斯拉执行长 Elon Musk 近日在一次公开谈话中再次表明了对&nbsp;AI 发展的担忧，他认为确保 AI 安全的成功率只有 5%-10% 。</p><p>Musk 认为&nbsp;AI 继续发展很大可能会产生毁灭性影响，他还点名&nbsp;Facebook 、Google 及 Amazon 这些网络已掌握超乎人们想像的数据量而形成一股强权。他指出，权力高度集中极其危险，如果智慧与人类相当的通用人工智能形成强大的权利，可能最终会落在这些超大公司的手里，且完全不受约束。</p><p>Musk 还另外成立了非营利组织，旨在研发对人类有益的 AI 技术，希望能抗衡如 Google DeepMind 的&nbsp; AI。同时，他还透露已在今年三月投资 DeepMind ，就是为了监督 Google AI 的发展。</p><p><img height="788" data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1124/160946_aKaA_2896879.png" src="https://static.oschina.net/uploads/space/2017/1124/160946_aKaA_2896879.png" width="1400"/></p>', '2017-12-06 23:49:12'),
  (35, '0', 'ExTiX 18.0 正式发布，基于 Ubuntu 的桌面 Linux 发行', 'https://www.oschina.net/news/90890/extix-18-0', '<p>ExTiX 18.0 正式发布了，ExTiX 是基于 Ubuntu 的桌面 Linux 发行。它具有 Deepin 桌面环境，基于 Ubuntu 17.10，与父软件库兼容。主要更新内容如下：</p><ul class=" list-paddingleft-2"><li><p>使用 Deepin 15.10 桌面环境，更美观、更易用、更安全</p></li><li><p>ExTiX Deepin 安装较少软件包，用户可根据需要自行下载</p></li><li><p>18.0 附带&nbsp;Refracta 工具，这是一个桌面工具，帮助用户创建自己的发行版本，可定制</p></li></ul><p>更多内容请查看<a href="http://www.extix.se/?p=340" target="_self">发布说明</a>。<br/></p><p>下载地址：<a href="http://downloads.sourceforge.net/extix/extix-18.0-64bit-deepin-refracta-1420mb-171123.iso">extix-18.0-64bit-deepin-refracta-1420mb-171123.iso</a> (1,457MB, <a href="http://downloads.sourceforge.net/extix/extix-64bit-deepin-refracta-1420mb-171123.md5">MD5</a>, <a href="http://distrowatch.com/dwres/torrents/extix-18.0-64bit-deepin-refracta-1420mb-171123.iso.torrent">torrent</a>, <a href="http://distrowatch.com/table.php?distribution=extix&pkglist=true&version=18.0#pkglist">pkglist</a>).</p>', '2017-12-06 23:49:12'),
  (36, '0', 'Wine 2.22 发布，Windows 应用兼容层', 'https://www.oschina.net/news/90889/wine-2-22', '<p>Wine 2.22&nbsp;已发布。Wine （“Wine Is Not an Emulator” 的首字母缩写）是一个能够在多种 POSIX-compliant 操作系统（诸如 Linux，macOS 及 BSD 等）上运行 Windows 应用的兼容层。Wine 不是像虚拟机或者模拟器一样模仿内部的 Windows 逻辑，而是将&nbsp;Windows API 调用翻译成为动态的 POSIX 调用，免除了性能和其他一些行为的内存占用，让你能够干净地集合 Windows 应用到你的桌面。<br/></p><p>更新内容：</p><ul class=" list-paddingleft-2"><li><p>Source selection dialog for scanners.</p></li><li><p>Improvements in ARM64 support.</p></li><li><p>Float audio formats with more than 2 channels in XAudio.</p></li><li><p>Fixes for DLL injection support.</p></li><li><p>Input methods improvements.</p></li><li><p>Various bug fixes.</p></li></ul><p>下载地址：</p><ul class=" list-paddingleft-2"><li><p><a href="https://www.winehq.org//download" _src="https://www.winehq.org//download">https://www.winehq.org//download</a>&nbsp; <br/></p></li></ul>', '2017-12-06 23:49:12'),
  (37, '0', 'KDevelop 5.2.1 发布，集成单元测试工具', 'https://www.oschina.net/news/90888/kdevelop-5-2-1', '<p>KDevelop 5.2.1 发布了。这是一个 Bug 修复版本，比 5.2.0 更安全，但并没有引入新功能。主要更新内容如下：</p><ul class=" list-paddingleft-2"><li><p>修复在 C ++ 项目中的背景的 git 分支时经常发生的崩溃的问题。 This temporarily disables documentation \nwarnings, as well as parsed documentation display in the tooltips, until\n the underlying issue is fixed upstream. (<a target="_blank" href="https://bugs.kde.org/show_bug.cgi?id=358205">bug</a>, <a target="_blank" href="https://bugs.llvm.org/show_bug.cgi?id=35333">upstream bug</a>)</p></li><li><p>修复在 Windows 上默认没有设置编译器，导致 KDevelop 无法找到 C ++ 标准库的问题。 (<a target="_blank" href="https://bugs.kde.org/show_bug.cgi?id=377045">bug</a>)</p></li><li><p>修正在窗口上使用 clang 作为编译器时，不传递包含路径的标准库路径的问题。(<a target="_blank" href="https://phabricator.kde.org/D8831">review</a>)</p></li></ul><p>更多内容请查看<a href="https://www.kdevelop.org/news/kdevelop-521-released" target="_self">发布说明</a>。<br/></p><p>下载地址：</p><ul class=" list-paddingleft-2"><li><p><a href="https://www.kdevelop.org/download" _src="https://www.kdevelop.org/download">https://www.kdevelop.org/d', '2017-12-06 23:49:12'),
  (38, '0', 'Element 1.4.11 发布，基于 Vue 2.0 的组件库', 'https://www.oschina.net/news/90887/element-1-4-11', '<p>Element 1.4.11 发布了。主要更新内容如下：</p><ul class=" list-paddingleft-2"><li><p>修复 Pagination 的页码输入框不对非法值进行修正的问题，<a href="https://github.com/ElemeFE/element/pull/8408" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="275593743" data-permission-text="Issue title is private" data-url="https://github.com/ElemeFE/element/issues/8408">#8408</a>（by <a href="https://github.com/decadef20" class="user-mention">@decadef20</a>）</p></li><li><p>修复被隐藏的 Table 会造成 CPU 占用持续增加的问题，<a href="https://github.com/ElemeFE/element/pull/8484" class="issue-link js-issue-link tooltipped tooltipped-ne" data-error-text="Failed to load issue title" data-id="276542121" data-permission-text="Issue title is private" aria-label="#8484, Table: fix high CPU consumption">#8484</a></p></li></ul><h2></h2><ul class=" list-paddingleft-2"><li><p>Now Pagination&#39;s jumper will correct invalid page inputs, <a href="https://github.com/ElemeFE/element/pull/8408" class="issue-link js-issue-link" data-error-text="Failed to l', '2017-12-06 23:49:12'),
  (39, '0', 'Gradle 4.4 RC2 发布，项目自动化构建工具', 'https://www.oschina.net/news/90886/gradle-4-4-rc2', '<p>Gradle 4.4 RC2 发布了。主要更新内容如下：</p><ul class=" list-paddingleft-2"><li><p><a target="_blank" class="issue-link js-issue-link" href="https://github.com/gradle/gradle/issues/3576">#3576</a>: Dependency resolution can fail if a parent POM contains a <em>dependency management</em> entry without version.</p></li><li><p><a target="_blank" class="issue-link js-issue-link" href="https://github.com/gradle/gradle/issues/3589">#3589</a>: NullPointerException when applying shadow plugin 1.2.4</p></li></ul><p>详细更新内容请查看<a href="https://docs.gradle.org/4.4-rc-2/release-notes" target="_self">发布说明</a>。<br/></p><p>升级方式：<br/></p><ol class=" list-paddingleft-2"><li><p><code>./gradlew wrapper --gradle-version=4.4-rc-2</code></p></li><li><p>下载独立安装包：<a target="_blank" href="https://gradle.org/release-candidate/" rel="nofollow">https://gradle.org/release-candidate/</a><br/></p></li></ol>', '2017-12-06 23:49:12'),
  (40, '0', 'Angular.js 1.6.7 发布，Web 前端框架', 'https://www.oschina.net/news/90885/angularjs-1-6-7', '<p>﻿Angular.js 1.6.7 发布了。主页更新内容如下：</p><h3>Bug 修复</h3><ul class=" list-paddingleft-2"><li><p>$compile:&nbsp;用指令名清理特殊字符 (<a href="https://github.com/angular/angular.js/commit/c4003fd03489f876b646f06838f4edb576bacf6f">c4003f</a>,&nbsp;<a href="https://github.com/angular/angular.js/issues/16314">#16314</a>,&nbsp;<a href="https://github.com/angular/angular.js/issues/16278">#16278</a>)</p></li><li><p>$location:&nbsp;不在 HTML5 模式下解码路径中的正斜杠 (<a href="https://github.com/angular/angular.js/commit/e06ebfdbb558544602fe9da4d7d98045a965f468">e06ebf</a>,&nbsp;<a href="https://github.com/angular/angular.js/issues/16312">#16312</a>)</p></li><li><p>sanitizeUri:&nbsp;清理包含IDEOGRAPHIC SPACE字符的URI (<a href="https://github.com/angular/angular.js/commit/ddeb1df15a23de93eb95dbe202e83e93673e1c4e">ddeb1d</a>,&nbsp;<a href="https://github.com/angular/angular.js/issues/16288">#16288</a>)</p></li></ul><h3>新功能</h3><ul class=" list-paddingleft-2"><li><p>$sanitize, $compileProvider, linky:&nbsp;在链接中添加对“sftp”协议的支持(<a href="https://github.com/a', '2017-12-06 23:49:12'),
  (41, '0', 'ArangoDB v3.3.rc3 发布，多模式数据库', 'https://www.oschina.net/news/90884/arangodb-3-3-rc', '<p>ArangoDB v3.3.rc3 发布了。ArangoDB&nbsp;是一个开源的分布式原生多模型数据库 (Apache 2 license)。</p><h3>理念&nbsp;&nbsp;</h3><p>利用一个引擎，一个 query 语法，一项数据库技术，以及多个数据模型，来最大力度满足项目的灵活性，简化技术堆栈，简化数据库运维，降低运营成本。</p><p>ArangoDB原生多模型数据库，指的是兼有图 (graph)、文档 (document)和键/值对 (key/value) 三种数据模型存储软件。其快捷灵活之处在于，它有适用于全部三种数据模型的统一内核和统一数据库查询语言——<a data-cke-saved-href="https://www.arangodb.com/why-arangodb/sql-aql-comparison/" href="https://www.arangodb.com/why-arangodb/sql-aql-comparison/">AQL&nbsp;</a>(ArangoDB Query Language)。其可以涵盖全部三种数据模型，还允许在单个查询中混合使用三种数据模型。</p><p>因此，用户可以在单次查询过程中混合使用多种数据模型，而无需在不同数据模型间相互“切换”，也不需要执行数据传输过程。并且这三种数据模型均支持水平扩展。基于其本地集成多模型特性，ArangoDB 原生多模型数据库适用于搭建高性能应用程序。</p><p>该版本更新内容请关注 <a href="https://github.com/arangodb/arangodb/blob/devel/CHANGELOG" target="_self">ChangeLog</a> 或<a href="https://github.com/arangodb/arangodb/releases/tag/v3.3.rc3" target="_self">发布主页</a>。<br/></p><p>下载地址：</p><ul class=" list-paddingleft-2"><li><p><a href="https://github.com/arangodb/arangodb/archive/v3.3.rc3.zip" rel="nofollow"><strong>Source code</strong>', '2017-12-06 23:49:12'),
  (42, '0', 'Linux Kernel 4.13.16, 4.9.65, 4.4.102 等五版齐发', 'https://www.oschina.net/news/90883/linux-kernel-41', '<p>Linux Kernel 4.13.16, 4.9.65, 4.14.2,3.18.84,4.4.102 发布了。</p><p>更新内容：</p><table><tbody><tr class="firstRow"><th align="right">Version:</th><td><strong>3.18.84 (EOL)</strong> (longterm)</td></tr><tr><th align="right">Released:</th><td>2017-11-24</td></tr><tr><th align="right">Source:</th><td><a target="_blank" href="https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.18.84.tar.xz">linux-3.18.84.tar.xz</a></td></tr><tr><th align="right">PGP Signature:</th><td><a target="_blank" href="https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.18.84.tar.sign">linux-3.18.84.tar.sign</a></td></tr><tr><th align="right">Patch:</th><td><a target="_blank" href="https://cdn.kernel.org/pub/linux/kernel/v3.x/patch-3.18.84.xz">full</a> (<a target="_blank" href="https://cdn.kernel.org/pub/linux/kernel/v3.x/incr/patch-3.18.83-84.xz">incremental</a>)</td></tr><tr><th align="right">ChangeLog:</th><td><a target="_blank" href="https://cdn.kernel.org/pub/linux/kernel/v3.x/ChangeLog-3.18.84">ChangeLog-3.18.84</a></td></tr></tbody></', '2017-12-06 23:49:12'),
  (43, '0', 'BlackArch Linux 2017.11.24 发布，包含诸多升级', 'https://www.oschina.net/news/90882/blackarch-linux', '<p>BlackArch Linux 2017.11.24 发布了。</p><p>主要更新内容如下：</p><ul class=" list-paddingleft-2"><li><p>添加50多个新工具</p></li><li><p>BlackArch 安装程序升级至 0.6</p></li><li><p>内核升级至 4.13.12</p></li><li><p>更新所有软件包及系统包</p></li><li><p>更新窗口管理菜单</p></li></ul><p>更多内容请查看<a href="https://blackarch.org/blog.html" target="_self">发布说明</a>。<br/></p><p>下载地址：</p><ul class=" list-paddingleft-2"><li><p><a href="https://blackarch.org/downloads.html" _src="https://blackarch.org/downloads.html">https://blackarch.org/downloads.html</a>&nbsp;</p></li></ul><p>BlackArch Linux 是一份基于 Arch Linux 的发行，它被设计为服务于系统渗透测试人员及安全研究人员。它的提供形式是一张自启动运行DVD镜像，包含有多个轻量级窗口管理器如 Fluxbox、Openbox、Awesome、spectrwm。它预装了一千多种专用工具以用于渗透测试和计算机取证分析。&nbsp;</p><p><img src="https://static.oschina.net/uploads/space/2017/0616/130612_Tsaj_2720166.png"/></p>', '2017-12-06 23:49:12'),
  (44, '0', 'foobar2000 1.3.17 正式版发布，音频播放器', 'https://www.oschina.net/news/90881/foobar-2000-1-3', '<p><strong>foobar2000是一款Windows \n平台下的高级音频播放器，包含了一些播放增益支持、低内存占用等基本特色以及内置支持一些流行的音频格式，支持强大的界面扩展和插件以及出色的音效。</strong>foobar2000的定位是专业数字音频播放工具，是一款出色的播放器。foobar2000 1.2支持UPnP \nMediaRenderer设备即插即用，使用FFmpeg进行MP3、AAC和Vorbis解码。</p><p><strong>fооbаr2000 1.3.17 Fіnаl:</strong></p><ul class=" list-paddingleft-2"><li><p>Fіхеd hоrrіblе, hоrrіblе bug wіth Сtrl+А “ѕеlесt аll” hаndlеr іn еdіt bохеѕ ѕtеаlіng аltgr+а mаkіng іt іmроѕѕіblе tо tуре “ą”.</p></li><li><p>Маdе роѕѕіblе tо rеtаg МР4/М4А fіlеѕ wіthоut ‘ftур’ hеаdеr.</p></li><li><p>Рrеvеntеd dесоdіng оf brоkеn МР3 frаmеѕ thаt оvеrlар wіth арраrеnt fіlе tаgѕ.</p></li><li><p>Аllоwеd dесоdіng оf WАV fіlеѕ wіth ѕаmрlе rаtеѕ аbоvе 1МНz.</p></li><li><p>Соnvеrtеr: Маdе fоrmаt lіѕt ѕоrtіng rеmеmbеrеd.</p></li><li><p>Fіхеd tаgѕ nоt bеіng rеаd frоm сеrtаіn WАV fіlеѕ.</p></li><li><p>Іntеrnаl fіхеѕ tо аllоw fоо_іnрut_ехе/fоо_іnрut_ffmреg dесоdіng оf НLЅ &amp; RТМР ѕtrеаmѕ.</p></li><li><p>Аddеd іntеrnаl ІМА АDРСМ dесоdеr fоr ѕресіfіс WАV fіlеѕ thаt ѕуѕtеm соdес rеfuѕеѕ tо рrосеѕѕ.</p><', '2017-12-06 23:49:12'),
  (45, '0', 'MongooseJS 4.13.5 发布，MongoDB 连接包', 'https://www.oschina.net/news/90880/mongoose-4-13-5', '<p>MongooseJS 4.13.5&nbsp;发布了，MongooseJS 是使用 JavaScript 编程，连接 MongoDB 数据库的软件包，使 MongoDB 的文档数据模型变的优雅起来，方便对 MongoDB 文档型数据库的连接和增删改查等常规数据操作。</p><p>更新内容：</p><ul class=" list-paddingleft-2"><li><p>fix(model): handle update cast errors correctly with bulkWrite #5845 <a href="https://github.com/Michael77">Michael77</a></p></li><li><p>docs: add link to bufferCommands option #5844 <a href="https://github.com/ralphite">ralphite</a></p></li><li><p>fix(model): allow virtual ref function to return arrays #5834 <a href="https://github.com/brunohcastro">brunohcastro</a></p></li><li><p>fix(query): don&#39;t throw uncaught error if query filter too big #5812</p></li><li><p>fix(document): if setting unselected nested path, don&#39;t overwrite nested path #5800</p></li><li><p>fix(document): support calling <code>populate()</code> on nested document props #5703</p></li><li><p>fix: add <code>strictBool</code> option for schema type boolean #5344 #5211 #4245</p></li><li><p>docs(faq): add faq re: typeKey #1886</p></li><li><p>docs(qu', '2017-12-06 23:49:12'),
  (46, '0', '支持 Angular 5！Wijmo 前端开发控件新版本正式上线', 'https://www.oschina.net/news/90879/wijmo-support-a', '<p>Angular 是谷歌用于构建移动和桌面 web 应用的 JavaScript 框架，一经推出即备受开发人员欢迎。Wijmo 是葡萄城公司出品的新一代 HTML 5 和 JavaScript UI 控件，也是全球率先支持 Angular 的控件集，因其快速灵活、零依赖性而闻名，能做到对 Angular、React、VueJS 和 TypeScript 的全面支持，正在被微软 Dynamics、Cisco 等公司和项目使用。</p><p>本月，Angular 5 正式发布，&nbsp;<a data-cke-saved-href="http://wijmo.gcpowertools.com.cn/" href="http://wijmo.gcpowertools.com.cn/" target="_blank">Wijmo&nbsp;</a>也迅速发布了支持 Angular 5 的最新版本，并对控件本身的主要性能和可访问性做了大量优化和支持！</p><h2>Wijmo 最新版本全面支持 Angular 5</h2><p>Wijmo 支持 Angular 所有的功能，允许用户在标记中声明整个控件，支持 Angular 绑定，甚至提供 FlexGrid 的单元模板，允许用户在标记中编写自定义单元格。本次新版本还提供许多模块格式的 Wijmo，所以用户可使用 Wijmo 与您所选择的 loader/packager 进行开发。</p><p><img data-cke-saved-src="https://images2018.cnblogs.com/blog/978677/201711/978677-20171124162621656-36229830.jpg" src="https://images2018.cnblogs.com/blog/978677/201711/978677-20171124162621656-36229830.jpg" alt="" width="603" height="208"/></p><h2>对 FlexGrid 性能的持续优化</h2><p>FlexGrid 是 Wijmo 中一个重要数据表格控件，本次新版本对其做了重大优化。以 Auto-Sizing 这个相对简单的任务为例：优化前使用的是安全但很基础的算法，创建一个不可见的 “measure” 输入元素，然后遍历行更新元素的', '2017-12-06 23:49:12'),
  (47, '0', 'PHP 支付类库 PaySDK v1.0.2，新增支付宝微信企业付款等', 'https://www.oschina.net/news/90878/paysdk-1-0-2', '<p>上周五发布了1.0.1版本后，反响强烈，都给PaySDK提了很多建议。本周主要是集成进了支付宝和微信的企业转账、海外支付功能，并且还修复了上一个版本的微信BUG。</p><p>PHP 支付类库 PaySDK v1.0.2 已发布，更新内容如下：</p><p>* 新增支持支付宝企业转账到支付宝账户、海外支付（电脑网站、手机网站、APP、扫码）、海关报关<br/><br/>* 新增支持微信企业付款到零钱、企业付款到银行卡、海外支付（刷卡、公众号、扫码、APP）、海关报关<br/><br/>* 修正签名方法命名<br/><br/>* 将微信企业付款接口强制设为使用MD5签名，因为微信只支持MD5<br/><br/>* 更新微信h5支付demo<br/><br/>* 调整微信通知写法<br/><br/>* 调整通知不合法提示<br/><br/>* 调整微信异步通知处理实现、修复BUG<br/><br/>* 优化代码</p><p>PaySDK 是 PHP 集成支付 SDK ，集成了支付宝、微信支付的支付接口和其它相关接口的操作。可以轻松嵌入支持 PHP &gt;= 5.3 的任何系统中。<br/><br/>我们有完善的在线技术文档：<a data-cke-saved-href="http://doc.yurunsoft.com/PaySDK" href="http://doc.yurunsoft.com/PaySDK" target="_blank">http://doc.yurunsoft.com/PaySDK</a><br/><br/>大家在开发中肯定会对接各种各样的支付平台，我个人精力有限，欢迎各位来提交 PR （<a data-cke-saved-href="https://gitee.com/yurunsoft/PaySDK" href="https://gitee.com/yurunsoft/PaySDK" target="_blank">码云</a>/<a data-cke-saved-href="https://github.com/Yurunsoft/PaySDK" href="https://github.com/Yurunsoft/PaySDK" target="_blank">Github</a>），一起完善 PaySDK ，让它能够支持更多的支付平台，更加好用。<br/><br/>有许多朋友', '2017-12-06 23:49:12'),
  (48, '0', 'SD 框架 2.7 版本发布助力企业开发', 'https://www.oschina.net/news/90877/swooledistribut', '<h3>选择SD框架助力企业开发</h3><p>今年年底历时2年多的迭代，这是SD框架硕果满满的一年，通过不断的迭代和改进SD框架已经在圈内有良好的口碑，不少新生的框架借鉴了SD的设计思想，SD框架也被不少创业型公司和大型企业使用。</p><p>最新一版的SD框架是2.7.1版本，最大的变化就是添加了一个集群管理界面，可以通过可视化的界面监控集群服务器的运行状态，并进行一些查询操作。</p><p>其余更新如下：</p><pre>1.“$SYS”服务器监控专用订阅主题，开发者可以订阅$SYS主题获得服务器监控信息</pre><pre>2.服务器间的RPC由单向通知改为双向交互</pre><pre>3.增加Timer定时器，该定时器在多进程中共享，A进程创建了定时B进程可以取消定时，可以在Controller，Model中使用，但请注意有严格使用方式&nbsp;的规范，使用不当容易导致数据错乱。</pre><pre>4.UID现在不限制为int，可以使用String。</pre><p><br/></p><h3>SD框架到底是什么技术</h3><p>SD框架全称SwooleDistributed，从名称上看一个是Swoole一个是Distributed，他是基于Swoole扩展的可以分布式部署的应用服务器框架。<br/>借助于PHP的高效开发环境，Swoole的高性能异步网络通信引擎，以及其他的高可用的扩展和工具，SD框架提供给广大开发者一个稳定的高效的而且功能强大的应用服务器框架。</p><h3>入门成本</h3><p>老实的说相对比目前热门的FPM框架来说，SD的入门成本相对还是比较高的，因为设计理念不同以及和传统PHP-FPM环境完全不同的运行环境，对于长时间使用LAMP（LANP）技术的开发人员来说会有一段时间的适应期，如果开发应用简单涉及到的系统复杂度低，那么SD上手还是比较容易，根据简单的例子和文档几乎立即就能开启SD的探索之旅，但是如果开发的是复杂的应用那么SD包含的众多组件还是需要你慢慢熟悉上手的。</p><h3>SD框架到底包含哪些强大的功能呢</h3><p>我们这里列举下SD提供的各种各样的功能以及模块组件</p><ul class=" list-paddingleft-2"><li><p>混合协议<br/>SD框架支持长连接协议TCP，WebSocket，短连接协议HTTP，以及UDP。<br/>', '2017-12-06 23:49:12'),
  (49, '0', '葡萄城 ComponentOne 2017V3 版本发布', 'https://www.oschina.net/news/90876', '<p>日前，全球最大的控件提供商葡萄城宣布，<a data-cke-saved-href="http://www.gcpowertools.com.cn/products/componentone_studio_enterprise.htm" href="http://www.gcpowertools.com.cn/products/componentone_studio_enterprise.htm" target="_blank">ComponentOne 全功能控件套包</a>发布2017年度最后一次重大更新（2017V3版本），除了对图表、性能持续优化外，还新增表达式编辑器，能与FlexGrid、FlexChart等控件有效集成，大大加强了ComponentOne在数据处理方面的能力！</p><p><img data-cke-saved-src="https://images2018.cnblogs.com/blog/978677/201711/978677-20171124091901921-14576569.png" src="https://images2018.cnblogs.com/blog/978677/201711/978677-20171124091901921-14576569.png" alt=""/></p><h3>新增表达式编辑器，数据处理更容易</h3><p>新的表达式编辑器，可以帮助用户创建类似Excel的公式，用于像FlexGrid和C1DataGrid这样的ComponentOne控件中的数据。该控件分为两个组件：ExpressionEditor和EditorPanel。</p><p>其中，ExpressionEditor可单独使用，嵌入自定义过滤器或表格的单元格中，具备汇总、时间格式、数学函数、逻辑运算符等能力，还有智能提示、语法高亮、搜索功能、错误提示、结果预览等开箱即用的特性。</p><p><img data-cke-saved-src="https://images2018.cnblogs.com/blog/978677/201711/978677-20171124092318562-356808978.png" src="https://images2018.cnblogs.com/blog/978677/201711/978677-201711240923185', '2017-12-06 23:49:12'),
  (50, '0', 'uiw 1.3.3 发布，紧急 bug 修复', 'https://www.oschina.net/news/90875/uiw-1-3-3', '<h3>新版发布， 高品质的 UI 工具包，React 16+ 的组件库。<br/></h3><p><img data-cke-saved-src="https://static.oschina.net/uploads/space/2017/1124/100500_6dj2_811064.png" src="https://static.oschina.net/uploads/space/2017/1124/100500_6dj2_811064.png" alt="" width="600" height="455" border="0" hspace="0" vspace="0" title="" style="width: 600px; height: 455px;"/></p><p><strong>更新内容：</strong><br/></p><p>Bug 修复:</p><ul class=" list-paddingleft-2"><li><p>修复TimePicker组件下拉菜单默认选中值问题。&nbsp;<a data-cke-saved-href="https://github.com/uiw-react/uiw/commit/01847a802598483f7d22754140671a8b97c3c533" href="https://github.com/uiw-react/uiw/commit/01847a802598483f7d22754140671a8b97c3c533">01847a8</a></p></li><li><p>修复Slider组件拖拽按钮的提示被遮挡。&nbsp;<a data-cke-saved-href="https://github.com/uiw-react/uiw/commit/0480b4d46786a13020a2755f644a6d5f1d7ee981" href="https://github.com/uiw-react/uiw/commit/0480b4d46786a13020a2755f644a6d5f1d7ee981">0480b4d</a></p></li><li><p>修复复制Slider拖拽超出界限。&nbsp;<a data-cke-saved-href="https://github.com/uiw-react/uiw/commit/ece', '2017-12-06 23:49:12');
/*!40000 ALTER TABLE `news` ENABLE KEYS */;

-- Dumping structure for table rssx.user
DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` int(11) DEFAULT NULL,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table rssx.user: ~0 rows (approximately)
DELETE FROM `user`;
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

-- Dumping structure for table rssx.user_feed
DROP TABLE IF EXISTS `user_feed`;
CREATE TABLE IF NOT EXISTS `user_feed` (
  `user_id` int(11) NOT NULL,
  `feed_id` int(11) NOT NULL,
  PRIMARY KEY (`user_id`,`feed_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table rssx.user_feed: ~2 rows (approximately)
DELETE FROM `user_feed`;
/*!40000 ALTER TABLE `user_feed` DISABLE KEYS */;
INSERT INTO `user_feed` (`user_id`, `feed_id`) VALUES
  (0, 0),
  (0, 1);
/*!40000 ALTER TABLE `user_feed` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
